# Generated by Django 4.2.5 on 2023-10-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0002_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Orderdttm',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transactiondttm',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
