# Generated by Django 4.2.5 on 2023-10-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0003_alter_order_orderdttm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='Item_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
